spring:
  profiles:
    active: embedded
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    generateDdl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: 'jdbc:h2:~/test'
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  data:
    neo4j:
      URI: foooooooooo
      indexes:
        auto:
          dump:
            dir: 'target/var/'
            filename: 'indexes-auto.cypher'
      repositories:
        enabled: true
  dao:
    exceptiontranslation:
      enabled: true
