spring:
  jpa:
    generateDdl: true
    showSql: true
    hibernate:
      ddlAuto: create-drop
  data:
    neo4j:
      indexes:
        auto:
          dump:
            dir: 'target/var/'
            filename: 'indexes-auto.cypher'
      repositories:
        enabled: true
  dao:
    exceptiontranslation:
      enabled: true
---
spring:
  profiles: default
  data:
    neo4j:
      URI: asdfghijklmop
---
spring:
  profiles: remotes
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: 'jdbc:postgresql://localhost:5432/evaluator?user=evaluator&password=evaluatorpwd&schema=public&catalog=information_schema'
    jdbcUrl: 'jdbc:postgresql://localhost:5432/evaluator?user=evaluator&password=evaluatorpwd&schema=public&catalog=information_schema'
    username: evaluator
    password: evaluatorpwd
    driverClassName: 'org.postgresql.Driver'
    platform: postgresql
  data:
    neo4j:
      URI: bolt://127.0.0.1:7687
      username: neo4j
      password: secret
      encryption:
        level: NONE
      connection:
        pool:
          size: 50
        liveness:
          check:
            timeout: 240s
      verify:
        connection: true
 #   datasource:
 #     url: 'jdbc:postgresql://localhost:5432/evaluator?user=evaluator&password=evaluatorpwd&schema=public&catalog=information_schema'
 #     jdbcUrl: 'jdbc:postgresql://localhost:5432/evaluator?user=evaluator&password=evaluatorpwd&schema=public&catalog=information_schema'
 #     username: evaluator
 #     password: evaluatorpwd
 #     driverClassName: org.postgresql.Driver
 #     platform: postgresql
 #   jpa:
 #     databasePlatform: org.hibernate.dialect.PostgreSQL95Dialect
 #     openInView: true
 #     generateDdl: true
 #     showSql: true
 #     hibernate:
 #       ddlAuto: create-drop
 #     properties:
 #       hibernate:
 #         dialect: org.hibernate.dialect.PostgreSQL95Dialect
 #         globally_quoted_identifiers: true
 #         temp:
 #           use_jdbc_metadata_defaults: false

