spring:
  profiles:
    active: travis
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: 'jdbc:postgresql://localhost:5432/evaluator?user=evaluator&password=evaluatorpwd&schema=public&catalog=information_schema'
    username: evaluator
    password: evaluatorpwd
    driver-class-name: org.postgresql.Driver
    platform: postgresql
  data:
    neo4j:
      URI: bolt://127.0.0.1:7687
      username: neo4j
      password: neo4j
      encryption:
        level: NONE
      connection:
        pool:
          size: 50
        liveness:
          check:
            timeout: 240s
      verify:
        connection: true

